// <auto-generated />
using System;
using FctApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FctApp.Migrations
{
    [DbContext(typeof(FctDbContext))]
    [Migration("20200710225859_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FctApp.Database.Models.tblCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblPurchaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblCustomers");
                });

            modelBuilder.Entity("FctApp.Database.Models.tblProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("tblPurchaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tblPurchaseId");

                    b.ToTable("tblProducts");
                });

            modelBuilder.Entity("FctApp.Database.Models.tblPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("tblCustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tblCustomerId");

                    b.ToTable("tblPurchases");
                });

            modelBuilder.Entity("FctApp.Database.Models.tblProduct", b =>
                {
                    b.HasOne("FctApp.Database.Models.tblPurchase", "tblPurchase")
                        .WithMany("tblProducts")
                        .HasForeignKey("tblPurchaseId");
                });

            modelBuilder.Entity("FctApp.Database.Models.tblPurchase", b =>
                {
                    b.HasOne("FctApp.Database.Models.tblCustomer", null)
                        .WithMany("tblPurchases")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
